spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/rockfall_db
spring.datasource.username=postgres
spring.datasource.password=2006
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cv.service.base-url=http://localhost:8000

risk-engine.service.base-url=http://127.0.0.1:9000